apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: postgres-service
    app: demo-voting-app
spec:
  selector:
    app: postgres-app-pod
    name: demo-voting-app
  type: ClusterIP
  ports:
    - name: db
      port: 5432
      targetPort: 5432
