apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: demo-voting-app
spec:
  selector:
    name: redis-app-pod
    app: demo-voting-app
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
