apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod
  labels:
    app: voting-app-pod
    name: demo-voting-app
spec:
  containers:
    - name: voting-app
      image: kodekloud/examplevotingapp_vote:v1
      ports:
        - containerPort: 80
